project_name: elementary

builds:
  - id: elementary-darwin
    binary: elementary
    main: ./cmd/elementary/.
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]
    env: [ CGO_ENABLED=1, CC=o64-clang, CXX=o64-clang++ ]
  - id: elementary-linux
    binary: elementary
    main: ./cmd/elementary/.
    env: [ CGO_ENABLED=1, CC=arm-linux-gnueabihf-gcc, CXX=arm-linux-gnueabihf-g++, GOARM=7 ]
    goos: [ linux ]
    goarch: [ amd64, arm64 ]
  - id: elementary-windows
    binary: elementary
    main: ./cmd/elementary/.
    ldflags: [ "-extldflags '-static'" ]
    env: [ CGO_ENABLED=1, CC=x86_64-w64-mingw32-gcc, CXX=x86_64-w64-mingw32-g++ ]
    goos: [ windows ]
    goarch: [ amd64 ]

  - id: elementary-server-darwin
    binary: elementary-server
    main: ./cmd/elementary-server/.
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]
    env: [ CGO_ENABLED=1, CC=o64-clang, CXX=o64-clang++ ]
  - id: elementary-server-linux
    binary: elementary-server
    main: ./cmd/elementary-server/.
    env: [ CGO_ENABLED=1 ]
    goos: [ linux ]
    goarch: [ amd64 ]
  - id: elementary-server-windows
    binary: elementary-server
    main: ./cmd/elementary-server/.
    ldflags: [ "-extldflags '-static'" ]
    env: [ CGO_ENABLED=1, CC=x86_64-w64-mingw32-gcc, CXX=x86_64-w64-mingw32-g++ ]
    goos: [ windows ]
    goarch: [ amd64 ]

archives:
  - id: elementary-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds: [ elementary-darwin, elementary-linux, elementary-windows ]
    replacements: { darwin: macOS, linux: Linux, windows: Windows }
    format_overrides: [ { goos: windows, format: zip } ]
  - id: elementary-server-archive
    name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds: [ elementary-server-darwin, elementary-server-linux, elementary-server-windows ]
    replacements: { darwin: macOS, linux: Linux, windows: Windows }
    format_overrides: [ { goos: windows, format: zip } ]
release:
  extra_files:
    - glob: ./cmd/elementary-gui/output/*
brews:
  - name: elementary
    ids: [ elementary-archive ]
    tap: { owner: forensicanalysis, name: homebrew-tap }
    commit_author: { name: Jonas Plum, email: git@jonasplum.de }
    folder: Formula
    homepage: "https://github.com/forensicanalysis/elementary"
    description: "Process and show forensic artifacts (e.g. eventlogs, usb devices, network devices...)."
    license: "MIT"
    skip_upload: "auto"
  - name: elementary-server
    ids: [ elementary-server-archive ]
    tap: { owner: forensicanalysis, name: homebrew-tap }
    commit_author: { name: Jonas Plum, email: git@jonasplum.de }
    folder: Formula
    homepage: "https://github.com/forensicanalysis/elementary"
    description: "Process and show forensic artifacts (e.g. eventlogs, usb devices, network devices...)."
    license: "MIT"
    install: bin.install "elementary-server"
    skip_upload: "auto"
scoop:
  bucket: { owner: forensicanalysis, name: homebrew-tap }
  commit_author: { name: Jonas Plum, email: git@jonasplum.de }
  homepage: "https://github.com/forensicanalysis/elementary"
  description: "Process and show forensic artifacts (e.g. eventlogs, usb devices, network devices...)."
  license: MIT
  skip_upload: "auto"
nfpms:
  - replacements: { darwin: macOS, linux: Linux }
    homepage: "https://github.com/forensicanalysis/elementary"
    maintainer: Jonas Plum <git@jonasplum.de>
    description: "Process and show forensic artifacts (e.g. eventlogs, usb devices, network devices...)."
    license: MIT
    formats: [ apk, deb, rpm ]
