name: Release

on:
  release:
    types: [published]

jobs:
  elementary:
    name: elementary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - uses: actions/setup-python@v1
        with: {python-version: '3.8'}
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        run: go build .

      - name: Pack UNIX
        run: zip -r ${{ matrix.os }}.zip elementary*
        shell: bash
        if: matrix.os != 'windows-latest'
      - name: Pack Windows
        run: 7z a ${{ matrix.os }}.zip elementary*
        shell: bash
        if: matrix.os == 'windows-latest'

      - run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
        shell: bash
        id: release

      - name: Upload Windows
        id: upload-windows-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}.zip
          asset_name: windows.zip
          asset_content_type: application/zip
        if: matrix.os == 'windows-latest'
      - name: Upload macOS
        id: upload-macos-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}.zip
          asset_name: macos.zip
          asset_content_type: application/zip
        if: matrix.os == 'macos-latest'
      - name: Upload Linux
        id: upload-linux-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}.zip
          asset_name: linux.zip
          asset_content_type: application/zip
        if: matrix.os == 'ubuntu-latest'

      - name: Checkout forensicanalysis/homebrew-tap
        uses: actions/checkout@v2
        with:
          repository: forensicanalysis/homebrew-tap
          path: homebrew-tap
          ssh-key: ${{ secrets.TAP_DEPLOY_KEY }}
        if: matrix.os == 'windows-latest'
      - run: python ../.github/workflows/create_release.py $GITHUB_EVENT_PATH ${{ steps.upload-windows-release-asset.outputs.browser_download_url }}
        working-directory: homebrew-tap
        if: matrix.os == 'windows-latest'
        shell: bash
      - name: Update homebrew-tap
        run: |
          git config --global user.email "git@cugu.eu"
          git config --global user.name "Update Bot"
          git add Formular/elementary.rb elementary.json
          git commit -m "Update formulars"
          git push origin master
        working-directory: homebrew-tap
        if: matrix.os == 'windows-latest'
        shell: bash
