name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: bepsays/ci-goreleaser:1.16.0-2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - run: apt-get update && apt-get install -y gcc-arm*
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          version: latest
          args: release --rm-dist
